
# most of this is requirements for github.com/dontpanic92/wxGo cribbed from that project's .travis.yml

sudo: required
dist: trusty

language: go

go:
  - 1.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libxxf86vm-dev
      - libnotify-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libatk1.0-dev
      - libglib2.0-dev
      - libglib2.0-0
      - libglu1-mesa-dev
      - libjpeg-dev
      - libtiff-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libwebkitgtk-3.0-dev
      - vnc4server

install:
  - go get -x -t ./...
  - Xvnc :1 &

#install:
#  - sudo apt-get build-dep wxwidgets2.8
#
# symlink g++?




