# most of this is requirements for github.com/dontpanic92/wxGo cribbed from that project's appveyor.yml

version: 1.0.{build}
platform: x64
clone_folder: c:\project\src\github.com\rakslice\twitch-notifier-go
clone_depth: 5
environment:
  matrix:
  - GOROOT: c:\go17

build_script:
- cmd: >-
    set GOPATH=c:\project\

    set PATH=c:\msys64\mingw64\bin;%GOROOT%\bin;c:\project\bin;%PATH%

    go env

    go version

    echo %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    go get -x github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    cd src\twitchnotifier

    go generate -x

    cd ..\..

    go get -v -t -x .\\...

after_build:
  - 7z a twitch-notifier-go.zip c:\project\bin\twitchnotifier.exe
  - 7z a twitch-notifier-go.zip %APPVEYOR_BUILD_FOLDER%\README.md
  - 7z a twitch-notifier-go.zip %APPVEYOR_BUILD_FOLDER%\LICENSE
  - make_windows_installer.cmd

artifacts:
  - path: twitch-notifier-go.zip
    name: twitch-notifier-go windows 64-bit zip
  - path: twitchnotifier64.exe
    name: twitch-notifier-go windows 64-bit installer

test_script:
- cmd: >-
    set GOPATH=c:\project\

    set PATH=c:\msys64\mingw64\bin;%GOROOT%\bin;%PATH%

    go env

    go version

    echo %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    cd src\twitchnotifier

    go test -x
