package main

// Generated by wxg_to_golang at 2016-12-01 23:38:27.976000
// from C:\Users\Andrew Tonner\twitch-notifier\notifiergui\notifier_gui.wxg

import (
	"github.com/dontpanic92/wxGo/wx"
)

type MainStatusWindow struct {
	wx.Frame
	sizer_1 wx.BoxSizer
	sizer_3 wx.BoxSizer
	label_1 wx.StaticText
	list_online wx.ListBox
	label_2 wx.StaticText
	list_offline wx.ListBox
	label_3 wx.StaticText
	list_log wx.ListBox
	sizer_2 wx.BoxSizer
	label_status wx.StaticText
	bitmap_channel_logo wx.StaticBitmap
	sizer_5 wx.BoxSizer
	sizer_6 wx.BoxSizer
	button_options wx.Button
	button_reload_channels wx.Button
	button_quit wx.Button
	label_6 wx.StaticText
	label_head_game wx.StaticText
	label_head_up wx.StaticText
	label_head_started wx.StaticText
	label_channel_status wx.StaticText
	label_game wx.StaticText
	label_uptime wx.StaticText
	label_start_time wx.StaticText
}

type MainStatusWindowEvents interface {
	_on_list_online_gen(e wx.Event)
	_on_list_online_dclick(e wx.Event)
	_on_list_offline_gen(e wx.Event)
	_on_list_offline_dclick(e wx.Event)
	_on_options_button_click(e wx.Event)
	_on_button_reload_channels_click(e wx.Event)
	_on_button_quit(e wx.Event)
}

func initMainStatusWindow(eventInterface MainStatusWindowEvents) *MainStatusWindow {
	out := &MainStatusWindow{}
	out.Frame = wx.NewFrame(wx.NullWindow, wx.ID_ANY, "twitch-notifier")
	out.sizer_1 = wx.NewBoxSizer(wx.VERTICAL)
	out.sizer_3 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.label_1 = wx.NewStaticText(out, wx.ID_ANY, "Online")
	out.list_online = wx.NewListBox(out, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	out.label_2 = wx.NewStaticText(out, wx.ID_ANY, "Offline")
	out.list_offline = wx.NewListBox(out, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	out.label_3 = wx.NewStaticText(out, wx.ID_ANY, "Log")
	out.list_log = wx.NewListBox(out, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	out.sizer_2 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.label_status = wx.NewStaticText(out, wx.ID_ANY, "Status")
	out.bitmap_channel_logo = wx.NewStaticBitmap(out, wx.ID_ANY, wx.NullBitmap)
	out.sizer_5 = wx.NewBoxSizer(wx.VERTICAL)
	out.sizer_6 = wx.NewBoxSizer(wx.VERTICAL)
	out.button_options = wx.NewButton(out, wx.ID_ANY, "&Options", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Options")
	out.button_reload_channels = wx.NewButton(out, wx.ID_ANY, "&Reload Channels", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Reload Channels")
	out.button_quit = wx.NewButton(out, wx.ID_ANY, "&Quit", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Quit")
	out.label_6 = wx.NewStaticText(out, wx.ID_ANY, "Channel Description:")
	out.label_head_game = wx.NewStaticText(out, wx.ID_ANY, "Game:")
	out.label_head_up = wx.NewStaticText(out, wx.ID_ANY, "Up:")
	out.label_head_started = wx.NewStaticText(out, wx.ID_ANY, "Started:")
	out.label_channel_status = wx.NewStaticText(out, wx.ID_ANY, "")
	out.label_game = wx.NewStaticText(out, wx.ID_ANY, "")
	out.label_uptime = wx.NewStaticText(out, wx.ID_ANY, "")
	out.label_start_time = wx.NewStaticText(out, wx.ID_ANY, "")
	
	out.set_properties()
	out.do_layout()
	
	wx.Bind(out, wx.EVT_LISTBOX, eventInterface._on_list_online_gen, out.list_online.GetId())
	wx.Bind(out, wx.EVT_LISTBOX_DCLICK, eventInterface._on_list_online_dclick, out.list_online.GetId())
	wx.Bind(out, wx.EVT_LISTBOX, eventInterface._on_list_offline_gen, out.list_offline.GetId())
	wx.Bind(out, wx.EVT_LISTBOX_DCLICK, eventInterface._on_list_offline_dclick, out.list_offline.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_options_button_click, out.button_options.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_button_reload_channels_click, out.button_reload_channels.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_button_quit, out.button_quit.GetId())
	
	return out
}

func (out MainStatusWindow) do_layout() {
	out.sizer_1.Add(out.sizer_3, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.label_1, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.list_online, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.label_2, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.list_offline, 1, wx.EXPAND, 0)
	out.sizer_1.Add(out.label_3, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.list_log, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.sizer_2, 0, wx.EXPAND, 0)
	out.sizer_1.Add(out.label_status, 0, wx.EXPAND, 0)
	out.sizer_3.Add(out.bitmap_channel_logo, 0, wx.EXPAND, 0)
	out.sizer_3.AddSpacer(10)
	out.sizer_3.Add(out.sizer_5, 0, wx.EXPAND, 0)
	out.sizer_3.AddSpacer(10)
	out.sizer_3.Add(out.sizer_6, 1, wx.EXPAND, 0)
	out.sizer_2.Add(out.button_options, 0, 0, 0)
	out.sizer_2.Add(out.button_reload_channels, 0, 0, 0)
	out.sizer_2.AddSpacer(20)
	out.sizer_2.Add(out.button_quit, 0, 0, 0)
	out.sizer_5.Add(out.label_6, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_game, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_up, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_started, 1, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_channel_status, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_game, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_uptime, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_start_time, 1, wx.EXPAND, 0)
	out.Frame.SetSizer(out.sizer_1)
	out.Frame.Layout()
}

func (window MainStatusWindow) set_properties() {
	window.SetTitle("twitch-notifier")
	window.SetSize(wx.NewSize(788, 793))
	window.SetBackgroundColour(wx.NewColour(byte(240), byte(240), byte(240)))
	window.list_online.SetToolTip("Double-Click to open stream page")
	window.list_offline.SetToolTip("Double-Click to open channel page")
	window.bitmap_channel_logo.SetMinSize(wx.NewSize(128, 128))
}

