package main

// Generated by wxg_to_golang at 2017-02-26 18:03:38.028000
// from C:\Users\Andrew Tonner\Documents\twitch-notifier-go\src\twitchnotifier\notifier_gui.wxg

import (
	"github.com/rakslice/wxGo/wx"
)

type MainStatusWindow struct {
	wx.Frame
	sizer_1 wx.BoxSizer
	panel_1 wx.Panel
	sizer_7 wx.BoxSizer
	sizer_3 wx.BoxSizer
	label_1 wx.StaticText
	list_online wx.ListBox
	label_2 wx.StaticText
	list_offline wx.ListBox
	notebook_1 wx.Notebook
	sizer_2 wx.BoxSizer
	label_status wx.StaticText
	sizer_4 wx.BoxSizer
	sizer_5 wx.BoxSizer
	sizer_6 wx.BoxSizer
	notebook_1_pane_1 wx.Panel
	notebook_1_pane_2 wx.Panel
	button_options wx.Button
	button_reload_channels wx.Button
	button_quit wx.Button
	bitmap_channel_logo wx.StaticBitmap
	button_open_channel wx.Button
	label_6 wx.StaticText
	label_head_game wx.StaticText
	label_head_up wx.StaticText
	label_head_started wx.StaticText
	label_channel_status wx.StaticText
	label_game wx.StaticText
	label_uptime wx.StaticText
	label_start_time wx.StaticText
	sizer_9 wx.BoxSizer
	sizer_8 wx.BoxSizer
	list_stream_event_log SimpleHtmlListBox
	list_log wx.ListBox
}

type MainStatusWindowEvents interface {
	_on_list_online_gen(e wx.Event)
	_on_list_online_dclick(e wx.Event)
	_on_list_offline_gen(e wx.Event)
	_on_list_offline_dclick(e wx.Event)
	_on_options_button_click(e wx.Event)
	_on_button_reload_channels_click(e wx.Event)
	_on_button_quit(e wx.Event)
	_on_button_open_channel_click(e wx.Event)
}

func initMainStatusWindow(eventInterface MainStatusWindowEvents) *MainStatusWindow {
	out := &MainStatusWindow{}
	out.Frame = wx.NewFrame(wx.NullWindow, wx.ID_ANY, "twitch-notifier")
	out.sizer_1 = wx.NewBoxSizer(wx.VERTICAL)
	out.panel_1 = wx.NewPanel(out, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TAB_TRAVERSAL)
	out.sizer_7 = wx.NewBoxSizer(wx.VERTICAL)
	out.sizer_3 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.label_1 = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Online")
	out.list_online = wx.NewListBox(out.panel_1, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	out.label_2 = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Offline")
	out.list_offline = wx.NewListBox(out.panel_1, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	out.notebook_1 = wx.NewNotebook(out.panel_1, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, 0, "notebook_1")
	out.sizer_2 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.label_status = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Status")
	out.sizer_4 = wx.NewBoxSizer(wx.VERTICAL)
	out.sizer_5 = wx.NewBoxSizer(wx.VERTICAL)
	out.sizer_6 = wx.NewBoxSizer(wx.VERTICAL)
	out.notebook_1_pane_1 = wx.NewPanel(out.notebook_1, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TAB_TRAVERSAL)
	out.notebook_1_pane_2 = wx.NewPanel(out.notebook_1, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TAB_TRAVERSAL)
	out.button_options = wx.NewButton(out.panel_1, wx.ID_ANY, "&Options", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Options")
	out.button_reload_channels = wx.NewButton(out.panel_1, wx.ID_ANY, "&Reload Channels", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Reload Channels")
	out.button_quit = wx.NewButton(out.panel_1, wx.ID_ANY, "&Quit", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Quit")
	out.bitmap_channel_logo = wx.NewStaticBitmap(out.panel_1, wx.ID_ANY, wx.NullBitmap)
	out.button_open_channel = wx.NewButton(out.panel_1, wx.ID_ANY, "&Open Channel", wx.DefaultPosition, wx.DefaultSize, 0, wx.DefaultValidator, "&Open Channel")
	out.label_6 = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Channel Description:")
	out.label_head_game = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Game:")
	out.label_head_up = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Up:")
	out.label_head_started = wx.NewStaticText(out.panel_1, wx.ID_ANY, "Started:")
	out.label_channel_status = wx.NewStaticText(out.panel_1, wx.ID_ANY, "")
	out.label_game = wx.NewStaticText(out.panel_1, wx.ID_ANY, "")
	out.label_uptime = wx.NewStaticText(out.panel_1, wx.ID_ANY, "")
	out.label_start_time = wx.NewStaticText(out.panel_1, wx.ID_ANY, "")
	out.sizer_9 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.sizer_8 = wx.NewBoxSizer(wx.HORIZONTAL)
	out.list_stream_event_log = NewSimpleHtmlListBox(out.notebook_1_pane_1, wx.ID_ANY)
	out.list_log = wx.NewListBox(out.notebook_1_pane_2, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, []string {})
	
	out.set_properties()
	out.do_layout()
	
	wx.Bind(out, wx.EVT_LISTBOX, eventInterface._on_list_online_gen, out.list_online.GetId())
	wx.Bind(out, wx.EVT_LISTBOX_DCLICK, eventInterface._on_list_online_dclick, out.list_online.GetId())
	wx.Bind(out, wx.EVT_LISTBOX, eventInterface._on_list_offline_gen, out.list_offline.GetId())
	wx.Bind(out, wx.EVT_LISTBOX_DCLICK, eventInterface._on_list_offline_dclick, out.list_offline.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_options_button_click, out.button_options.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_button_reload_channels_click, out.button_reload_channels.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_button_quit, out.button_quit.GetId())
	wx.Bind(out, wx.EVT_BUTTON, eventInterface._on_button_open_channel_click, out.button_open_channel.GetId())
	
	return out
}

func (out MainStatusWindow) do_layout() {
	out.sizer_1.Add(out.panel_1, 1, wx.EXPAND, 0)
	out.panel_1.SetSizer(out.sizer_7)
	out.sizer_7.Add(out.sizer_3, 0, wx.EXPAND, 0)
	out.sizer_7.Add(out.label_1, 0, wx.EXPAND, 0)
	out.sizer_7.Add(out.list_online, 0, wx.EXPAND, 0)
	out.sizer_7.Add(out.label_2, 0, wx.EXPAND, 0)
	out.sizer_7.Add(out.list_offline, 1, wx.EXPAND, 0)
	out.sizer_7.Add(out.notebook_1, 1, wx.EXPAND, 0)
	out.sizer_7.Add(out.sizer_2, 0, wx.EXPAND, 0)
	out.sizer_7.Add(out.label_status, 0, wx.EXPAND, 0)
	out.sizer_3.Add(out.sizer_4, 0, wx.EXPAND, 0)
	out.sizer_3.AddSpacer(10)
	out.sizer_3.Add(out.sizer_5, 0, wx.EXPAND, 0)
	out.sizer_3.AddSpacer(10)
	out.sizer_3.Add(out.sizer_6, 1, wx.EXPAND, 0)
	out.notebook_1.AddPage(out.notebook_1_pane_1, "Streams Log")
	out.notebook_1.AddPage(out.notebook_1_pane_2, "Debug Log")
	out.sizer_2.Add(out.button_options, 0, 0, 0)
	out.sizer_2.Add(out.button_reload_channels, 0, 0, 0)
	out.sizer_2.AddStretchSpacer(1)
	out.sizer_2.Add(out.button_quit, 0, 0, 0)
	out.sizer_4.Add(out.bitmap_channel_logo, 0, wx.EXPAND, 0)
	out.sizer_4.Add(out.button_open_channel, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_6, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_game, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_up, 0, wx.EXPAND, 0)
	out.sizer_5.Add(out.label_head_started, 1, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_channel_status, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_game, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_uptime, 0, wx.EXPAND, 0)
	out.sizer_6.Add(out.label_start_time, 1, wx.EXPAND, 0)
	out.notebook_1_pane_1.SetSizer(out.sizer_9)
	out.notebook_1_pane_2.SetSizer(out.sizer_8)
	out.sizer_9.Add(out.list_stream_event_log, 1, wx.EXPAND, 0)
	out.sizer_8.Add(out.list_log, 1, wx.EXPAND, 0)
	out.Frame.SetSizer(out.sizer_1)
	out.Frame.Layout()
}

func (window MainStatusWindow) set_properties() {
	window.SetTitle("twitch-notifier")
	window.SetSize(wx.NewSize(788, 793))
	window.SetBackgroundColour(wx.NewColour(byte(240), byte(240), byte(240)))
	window.list_online.SetToolTip("Double-Click to open stream page")
	window.list_offline.SetToolTip("Double-Click to open channel page")
	window.button_options.Enable(false)
	window.bitmap_channel_logo.SetMinSize(wx.NewSize(128, 128))
	window.button_open_channel.Enable(false)
}

